FROM ekidd/rust-musl-builder:1.57.0 as builder
USER root
RUN apt update && apt upgrade -y && apt install -y git
RUN rustup component add rustfmt
RUN mkdir /rustica
COPY proto /tmp/proto
COPY rustica /tmp/rustica
WORKDIR /tmp/rustica

RUN cargo build --release

from scratch as runtime
COPY --from=builder /tmp/rustica/target/x86_64-unknown-linux-musl/release/rustica /rustica
COPY examples/rustica_external.toml /etc/rustica/rustica.toml
USER 1000
ENTRYPOINT [ "/rustica" ]
