version = 2
key = """
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5AAAAKBcmh6OXJoe
jgAAAAtzc2gtZWQyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5A
AAAEAadOY5EF0mGYUOXxRvfpBJOzBu8IXLVS+UJ95dFDfAuu6eVuCxh3eCENKcLWNtmheS
3S7sBgh3+Wkd6YNL3gzkAAAAGW9iZWxpc2tAbWl0Y2hlbGxzLW1icC5sYW4BAgME
-----END OPENSSH PRIVATE KEY-----
"""
socket = "/tmp/rustica_socket_dev3"

[[servers]]
address = "https://localhost:50052"
ca_pem = """
-----BEGIN CERTIFICATE-----
MIIBJDCBzAIJAJGDT3qxW0/TMAoGCCqGSM49BAMCMBsxGTAXBgNVBAMMEEVudGVy
cHJpc2VSb290Q0EwHhcNMjIwMTIwMDQwMjA2WhcNMzIwMTE4MDQwMjA2WjAbMRkw
FwYDVQQDDBBFbnRlcnByaXNlUm9vdENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAErbw3gSqNpSsz75hQxDLkvMA3u4b+wnM9ha+2c6hJ3q3Dv+fpcX43FYoMud4u
o36dlMy3bUXbw5Kd6yGOMu+BfTAKBggqhkjOPQQDAgNHADBEAiBXa5LdA+F/qc73
56fvs1qMmjOTp8u6haFQ6MVTfOXYRgIgTAr4/kwoxyGSCd0z4Ehgud+J2PClDhad
HaLQ5dcIBw8=
-----END CERTIFICATE-----
"""
mtls_cert = """
-----BEGIN CERTIFICATE-----
MIIBVjCB3KADAgECAghPhuBjlTGcpDAKBggqhkjOPQQDAzAYMRYwFAYDVQQDDA1S
dXN0aWNhQWNjZXNzMB4XDTIzMDUyNjA3MjgzOVoXDTI5MDIyMzA3MjgzOVowEjEQ
MA4GA1UEAwwHb2JlbGlzazBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCTeMGsm
eW8IgcCow/MQh0ELcRL70xHJes8jlWCVbcCkBJzuYoaXHBWsczmzlMfJZ6fiYayF
XY7zeki+b+IukzOjFjAUMBIGA1UdEQQLMAmCB29iZWxpc2swCgYIKoZIzj0EAwMD
aQAwZgIxAIYLibYaxzcbZ0K9IWdIcOhnh8fvDW+Xozp1nU3++mhsASE2cbgzgrx5
4i5VR4kymwIxAIip2AIVm9k3tMRmkX2nMdnL7wOKR+Hxhe0fdSabWXfvg2gKePjN
SNKgrPKT1OOoMQ==
-----END CERTIFICATE-----
"""
mtls_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgQVrtm8rEr9z5f15a
o89ijgIdfH+5kO6FkVPB2fU39U+hRANCAAQk3jBrJnlvCIHAqMPzEIdBC3ES+9MR
yXrPI5VglW3ApASc7mKGlxwVrHM5s5THyWen4mGshV2O83pIvm/iLpMz
-----END PRIVATE KEY-----
"""

[options]
principals = ["testuser"]
kind = "user"
duration = 15
authority = "example_test_environment"
