server = "https://localhost:50052"
socket = "/tmp/rustica_socket_dev"
ca_pem = '''
-----BEGIN CERTIFICATE-----
MIIBJjCBzAIJAMlBYu4XhGzkMAoGCCqGSM49BAMCMBsxGTAXBgNVBAMMEEVudGVy
cHJpc2VSb290Q0EwHhcNMjIwMTEzMDM0MTAyWhcNMzIwMTExMDM0MTAyWjAbMRkw
FwYDVQQDDBBFbnRlcnByaXNlUm9vdENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEwu3YojGoGyh9tC6TOF3GqdhclbqytjOm5oHYiNTX96jk8m4gMoZwpq98R1+n
SnVstTGu+TVdJGsyEzKVzekJtjAKBggqhkjOPQQDAgNJADBGAiEAkbDkf2Zaf1Bj
y5wNKVfm0A0wYs+kc0vCNu9ctGTwdE8CIQCENCvY8UGKKFTsIkdJH8gzTkqqFA/D
Os3ds9BMGEbwWg==
-----END CERTIFICATE-----
'''
key = '''
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5AAAAKBcmh6OXJoe
jgAAAAtzc2gtZWQyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5A
AAAEAadOY5EF0mGYUOXxRvfpBJOzBu8IXLVS+UJ95dFDfAuu6eVuCxh3eCENKcLWNtmheS
3S7sBgh3+Wkd6YNL3gzkAAAAGW9iZWxpc2tAbWl0Y2hlbGxzLW1icC5sYW4BAgME
-----END OPENSSH PRIVATE KEY-----
'''

mtls_cert = '''
-----BEGIN CERTIFICATE-----
MIIBljCCAT2gAwIBAgIJAK6mSGvGGgl/MAoGCCqGSM49BAMCMCExHzAdBgNVBAMM
FkVudGVycHJpc2VDbGllbnRSb290Q0EwHhcNMjIwMTEzMDM1NTA4WhcNMjQwNDE3
MDM1NTA4WjATMREwDwYDVQQDDAh0ZXN0dXNlcjBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABBJR3whBZCUctJXYrxz5dtr0Ruu+OUjNUYag1yLZuVctyyRxwxfoqSRl
FF8r9Tlig12WJrqGzKkZShyb4ky3PNqjbDBqMDsGA1UdIwQ0MDKhJaQjMCExHzAd
BgNVBAMMFkVudGVycHJpc2VDbGllbnRSb290Q0GCCQDr6L6oQ8QxzjAJBgNVHRME
AjAAMAsGA1UdDwQEAwIE8DATBgNVHREEDDAKggh0ZXN0dXNlcjAKBggqhkjOPQQD
AgNHADBEAiAcCJbwWBJkJ/V8hkFfb5lYdN53eKtheClvI8PMklhi9wIgOqizzOJR
I/h9GV0CZ22pLwjRnVABCy9/UwSghgrRoVg=
-----END CERTIFICATE-----
'''

mtls_key = '''
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgmbUZmCwwdljaBK5u
s/OdgxLTf8yC7Ugm7vpOx/yA8O6hRANCAAQSUd8IQWQlHLSV2K8c+Xba9EbrvjlI
zVGGoNci2blXLcskccMX6KkkZRRfK/U5YoNdlia6hsypGUocm+JMtzza
-----END PRIVATE KEY-----
'''

[options]
duration = 15
principals = ["testuser"]
kind = "user"