version = 2
key = """
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5AAAAKBcmh6OXJoe
jgAAAAtzc2gtZWQyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5A
AAAEAadOY5EF0mGYUOXxRvfpBJOzBu8IXLVS+UJ95dFDfAuu6eVuCxh3eCENKcLWNtmheS
3S7sBgh3+Wkd6YNL3gzkAAAAGW9iZWxpc2tAbWl0Y2hlbGxzLW1icC5sYW4BAgME
-----END OPENSSH PRIVATE KEY-----
"""
socket = "/tmp/rustica_socket_dev3"

[[servers]]
address = "https://localhost:50052"
ca_pem = """
-----BEGIN CERTIFICATE-----
MIIBizCCATGgAwIBAgIUSxuBkb/vlm8p9VQRVlGeC7KWjQswCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQRW50ZXJwcmlzZVJvb3RDQTAeFw0yNDA2MDYwNDA4MThaFw0z
NDA2MDQwNDA4MThaMBsxGTAXBgNVBAMMEEVudGVycHJpc2VSb290Q0EwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAAQhZaDE0x7484SonAR5Ogufm7Qg5CttNfOr6Lk4
uqmJaUpxNsFJOclZqGUHgIPMfK7qQIU0K8EDD+mxJBIYY2V5o1MwUTAdBgNVHQ4E
FgQUOhiiXYkz9/H/i5F87/PRfqg/6E4wHwYDVR0jBBgwFoAUOhiiXYkz9/H/i5F8
7/PRfqg/6E4wDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiBm3CqE
bvVHnNt5gd4NDUkJ3ALrp3pzm24UFJU/sRssEgIhAKsSFHVza/vSJ/6KWqvZoogB
DF1DluRk6qknMiXlDjpI
-----END CERTIFICATE-----
"""
mtls_cert = """
-----BEGIN CERTIFICATE-----
MIIBozCCAUmgAwIBAgIUFfYNR8USdd5H7aedW/EhejTq9acwCgYIKoZIzj0EAwIw
ITEfMB0GA1UEAwwWRW50ZXJwcmlzZUNsaWVudFJvb3RDQTAeFw0yNDA2MDYwNDEw
MDlaFw0yNjA5MDkwNDEwMDlaMBIxEDAOBgNVBAMMB29iZWxpc2swWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQ0J0nZiZPzoXF0RuevlbxEMIO8mmppKF8vcoloU7en
vcT/Cof1NOu1/bka6vP1gvz6dhcLCKxov+lNj5FlSodzo24wbDAfBgNVHSMEGDAW
gBRMuJfTYkBiJshpOzKAqC13Ae0jTTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIE8DAS
BgNVHREECzAJggdvYmVsaXNrMB0GA1UdDgQWBBQY/OwzJcXMf6CTFiZThdIpq6fs
aTAKBggqhkjOPQQDAgNIADBFAiEA578eo2QJmnOEbkFUz/ADoWbgcfiYl2yWQ6iZ
dGIrZgwCIENWYLP38Gco2hSTfhkdC//D1+/+3XHBIoL5/WKXImbD
-----END CERTIFICATE-----
"""
mtls_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgdmdE/mTtZQt7bECc
19jWc96c6go4kU4KE5OzxO/Fys+hRANCAAQ0J0nZiZPzoXF0RuevlbxEMIO8mmpp
KF8vcoloU7envcT/Cof1NOu1/bka6vP1gvz6dhcLCKxov+lNj5FlSodz
-----END PRIVATE KEY-----
"""

[options]
principals = ["testuser"]
kind = "user"
duration = 15
authority = "example_test_environment"
