version = 2
# Generate a renewal CSR once our mTLS cert is this close to expiring. Matches
# the test server's expiration_renewal_period so the integration test exercises
# key retaining renewal.
mtls_csr_renewal_period = 181439980
key = """
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5AAAAKBcmh6OXJoe
jgAAAAtzc2gtZWQyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5A
AAAEAadOY5EF0mGYUOXxRvfpBJOzBu8IXLVS+UJ95dFDfAuu6eVuCxh3eCENKcLWNtmheS
3S7sBgh3+Wkd6YNL3gzkAAAAGW9iZWxpc2tAbWl0Y2hlbGxzLW1icC5sYW4BAgME
-----END OPENSSH PRIVATE KEY-----
"""
socket = "/tmp/rustica_socket_dev3"

[[servers]]
address = "https://localhost:50052"
ca_pem = """
-----BEGIN CERTIFICATE-----
MIIBizCCATGgAwIBAgIUV8VRIF9joTe1D9CZ/Glq+w3RQbAwCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQRW50ZXJwcmlzZVJvb3RDQTAeFw0yNDA2MDUwNTM3MjRaFw0z
NDA2MDMwNTM3MjRaMBsxGTAXBgNVBAMMEEVudGVycHJpc2VSb290Q0EwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATKDnlT7KqZDlKzEqhLGvnHCVRVDNuDKgx2K12o
TWit6KkTv7HiFHHqhLBl+gWwrC5mFM8r088UfOl8FYrY1wtPo1MwUTAdBgNVHQ4E
FgQUbqjtv3IJLkjk8jqeJuoUb/q3zowwHwYDVR0jBBgwFoAUbqjtv3IJLkjk8jqe
JuoUb/q3zowwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiB2/E3M
9x98EzjnVrQQiVAgea9QTw9NxtnB/nAXyl4txgIhAKKuYdIrA2nBFp1lSUTw+MJS
r8G0NzMoxnWYCtNZc2Db
-----END CERTIFICATE-----
"""
mtls_cert = """
-----BEGIN CERTIFICATE-----
MIIBQDCB6KADAgECAhRbYYIDWEKT8IGx2ABwTEC+tQPqLDAKBggqhkjOPQQDAjAY
MRYwFAYDVQQDDA1SdXN0aWNhQWNjZXNzMB4XDTI2MDgxNzE5MjQwMFoXDTMyMDUx
NzE5MjQwMFowEjEQMA4GA1UEAwwHb2JlbGlzazBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABMBEUxwJ1VAuqp2ZBTiogSWI1ITz/D9P3TIuXzzobXg34j9IXlR45iO6
YrnhYLMcQckVSVOX25UhOl8z6Q8zEI6jFjAUMBIGA1UdEQQLMAmCB29iZWxpc2sw
CgYIKoZIzj0EAwIDRwAwRAIgfzW09GR3GMfIqE/LeiIerKbXVgi1yhFzCW2IhuGe
qXwCIGXWd41tV2MgzFftn4HuegcugSGxankiO28a8Nn650i/
-----END CERTIFICATE-----
"""
mtls_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkevOcS3LhybJnFUw
dHMaRDuXsJO6ltXj+2SqoZzJzjehRANCAATARFMcCdVQLqqdmQU4qIEliNSE8/w/
T90yLl886G14N+I/SF5UeOYjumK54WCzHEHJFUlTl9uVITpfM+kPMxCO
-----END PRIVATE KEY-----
"""

[options]
principals = ["testuser"]
kind = "user"
duration = 15
authority = "example_test_environment"
