version = 2
socket = "/tmp/rustica_socket_dev3"

key = '''
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5AAAAKBcmh6OXJoe
jgAAAAtzc2gtZWQyNTUxOQAAACDunlbgsYd3ghDSnC1jbZoXkt0u7AYId/lpHemDS94M5A
AAAEAadOY5EF0mGYUOXxRvfpBJOzBu8IXLVS+UJ95dFDfAuu6eVuCxh3eCENKcLWNtmheS
3S7sBgh3+Wkd6YNL3gzkAAAAGW9iZWxpc2tAbWl0Y2hlbGxzLW1icC5sYW4BAgME
-----END OPENSSH PRIVATE KEY-----
'''

[[servers]]
address = "https://localhost:50055"
ca_pem = '''
-----BEGIN CERTIFICATE-----
MIIBJDCBzAIJAJGDT3qxW0/TMAoGCCqGSM49BAMCMBsxGTAXBgNVBAMMEEVudGVy
cHJpc2VSb290Q0EwHhcNMjIwMTIwMDQwMjA2WhcNMzIwMTE4MDQwMjA2WjAbMRkw
FwYDVQQDDBBFbnRlcnByaXNlUm9vdENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAErbw3gSqNpSsz75hQxDLkvMA3u4b+wnM9ha+2c6hJ3q3Dv+fpcX43FYoMud4u
o36dlMy3bUXbw5Kd6yGOMu+BfTAKBggqhkjOPQQDAgNHADBEAiBXa5LdA+F/qc73
56fvs1qMmjOTp8u6haFQ6MVTfOXYRgIgTAr4/kwoxyGSCd0z4Ehgud+J2PClDhad
HaLQ5dcIBw8=
-----END CERTIFICATE-----
'''

mtls_cert = '''
-----BEGIN CERTIFICATE-----
MIIBlzCCAT2gAwIBAgIJAK5nUV57sq6lMAoGCCqGSM49BAMCMCExHzAdBgNVBAMM
FkVudGVycHJpc2VDbGllbnRSb290Q0EwHhcNMjIwMTIwMDQwMjM0WhcNMjQwNDI0
MDQwMjM0WjATMREwDwYDVQQDDAh0ZXN0dXNlcjBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABCUDWf0rUjB+XVSZP1hTfIlpZIcgJu4f51gmGhzWybDUpUOa23zKwowL
A2btjSLx61cnpEDyQF8d3Fa13cYQxLyjbDBqMDsGA1UdIwQ0MDKhJaQjMCExHzAd
BgNVBAMMFkVudGVycHJpc2VDbGllbnRSb290Q0GCCQC98iVCe0oTiTAJBgNVHRME
AjAAMAsGA1UdDwQEAwIE8DATBgNVHREEDDAKggh0ZXN0dXNlcjAKBggqhkjOPQQD
AgNIADBFAiBAGrjUa2TBIt5Kw6uS7jbR85HZImCKBSbe2MHLmmS4AwIhAL7tTZVI
qBvba+mGBNlKGwS0gD6Verx6oK2to7kcPPWZ
-----END CERTIFICATE-----
'''

mtls_key = '''
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXg6AOoecpU6+o8FB
yfXoGgvww6QZ4zphYEJcQVJlbNihRANCAAQlA1n9K1Iwfl1UmT9YU3yJaWSHICbu
H+dYJhoc1smw1KVDmtt8ysKMCwNm7Y0i8etXJ6RA8kBfHdxWtd3GEMS8
-----END PRIVATE KEY-----
'''

[options]
duration = 15
authority = "example_test_environment"
principals = ["testuser"]
kind = "user"