name: Dependency Checks

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
permissions:
  contents: read

jobs:
  dependency-age:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: timweri/cargo-oxidate@v0.1.5
      with:
        min-age-days: 14
