name: Integration Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v7
    - name: Install libpcsc
      run: sudo apt install -y libpcsclite-dev libusb-1.0-0-dev libudev-dev
    - name: Run Integration Tests
      run: ./tests/integration.sh
