name: Lint Checks

on:
  push:
    branches: [ master, develop ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v6

    - name: Install libpcsc
      run: sudo apt install -y libpcsclite-dev libusb-1.0-0-dev libudev-dev

    - name: Run cargo fmt check
      run: cargo fmt --check

    - uses: timweri/cargo-oxidate@5630341fca14f77a200402f6510f69adc63591f9 # v0.1.4
      with:
        min-age-days: 14
