name: Feature Compilation Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-build-with-all:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features=all

  ubuntu-build-with-splunk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features=splunk

  ubuntu-build-with-influx:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features=influx

  ubuntu-build-with-local-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features=local-db

  ubuntu-build-with-amazon-kms:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features=amazon-kms

  ubuntu-build-with-all-except-yubikey:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --package=rustica --features="splunk,influx,local-db,amazon-kms"
