name: Feature Compilation Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            features: all
          - os: ubuntu-latest
            features: splunk
          - os: ubuntu-latest
            features: influx
          - os: ubuntu-latest
            features: local-db
          - os: ubuntu-latest
            features: amazon-kms
          - os: ubuntu-latest
            features: splunk,influx,local-db,amazon-kms
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v7
    - name: Build
      run: cargo build --package=rustica --features=${{ matrix.features }}
